import './globals.css';
import Navigation from '@/components/layout/Navigation';


export const metadata = {
  title: 'My first app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
